[package]
name = "xdremux-codec"
version = "0.1.0"
edition.workspace = true

[dependencies]
libheif-rs = { version = "=2.7.0", default-features = false, features = ["v1_17"] }
xdremux-engine = { path = "../xdremux-engine" }
xdremux-format = { path = "../xdremux-format" }

[dev-dependencies]
xdremux-heif = { path = "../xdremux-heif" }

[lints]
workspace = true
