import Foundation

enum AppStrings {
    static let addHEIC = "添加 HEIC"
    static let addHEICHelp = "添加 HEIC 文件或文件夹"
    static let startConversion = "开始转换"
    static let cancel = "取消"
    static let conversionSettings = "转换设置"
    static let clearQueue = "清空队列"
    static let emptyQueueTitle = "拖入或添加 ProXDR HEIC 文件"
    static let queueNotImported = "未导入文件"
    static let retryFailed = "重试失败项"
    static let removeCompleted = "移除已完成"
    static let revealOutputsInFinder = "在访达中显示输出"
    static let revealInputInFinder = "在访达中显示源文件"
    static let revealInFinder = "在访达中显示"
    static let remove = "移除"
    static let noSelection = "选择队列中的文件查看预览与输出计划"
    static let preview = "预览"
    static let previewLoading = "正在生成预览..."
    static let previewUnavailable = "预览不可用"
    static let inputPath = "源文件"
    static let outputPath = "输出文件"
    static let fileStatus = "文件状态"
    static let outputPlan = "输出计划"
    static let outputPlanReady = "准备写入"
    static let outputPlanOverwriteExisting = "将覆盖已有文件"
    static let outputPlanSkipExisting = "已有有效输出，将跳过"
    static let outputPlanDuplicate = "输出路径冲突"
    static let outputPlanInputMissing = "源文件不存在"
    static let outputPlanParentIsFile = "输出目录位置是文件"

    static let statConverted = "成功"
    static let statSkipped = "已跳过"
    static let statFailed = "失败"
    static let statCancelled = "已取消"
    static let statTotal = "总计"

    static let concurrentJobsSummary = "并发"
    static let pending = "待处理"
    static let running = "运行中"
    static let ready = "准备就绪"
    static let queueReady = "队列就绪"
    static let scanning = "正在扫描"
    static let converting = "正在转换"
    static let conversionFinished = "转换完成"
    static let conversionFinishedWithFailures = "转换结束，部分文件失败"
    static let waitingForInput = "等待输入"

    static let selectHEICPanelMessage = "选择要加入队列的 ProXDR HEIC 文件或文件夹"
    static let select = "选择"

    static let statusPending = "待处理"
    static let statusRunning = "运行中"
    static let statusConverted = "成功"
    static let statusSkippedExisting = "已跳过"
    static let statusFailed = "失败"
    static let statusCancelled = "已取消"

    static let standardHDR = "标准 ISO HDR"
    static let oppoGalleryCompatibility = "输出 OPPO 相册兼容格式"
    static let oppoGalleryCompatibilityShort = "OPPO 兼容 HDR"
    static let oppoGalleryCompatibilityHelp = "默认关闭并输出标准 ISO HDR；开启后交给 Rust 的 OPPO compatibility intent，生成 OPPO 相册可消费的 Main Still 4:2:0 Gain Map。"
    static let applePhotographicStyles = "Apple 摄影风格"
    static let applePhotographicStylesHelp = "从当前照片生成可逆 StyleEngine 系数、Linear Thumbnail、语义蒙版和 Style Delta；不读取 Apple donor 照片。需要当前 macOS 的私有 Apple Learn/Vision 运行时。"
    static let applePortrait = "Apple 人像编辑"
    static let applePortraitHelp = "使用 OPPO 景深数据与当前照片的 Vision person、skin、hair、teeth、glasses 分割结果生成 Apple 人像辅助项目。非人像照片仍可单独输出摄影风格。"
    static let appleFeaturesOppoIncompatibleHelp = "Apple 输出与 OPPO 相册兼容层互斥；先关闭 OPPO 相册兼容格式。"
    static let skipExisting = "跳过已有有效输出"
    static let skipExistingHelp = "目标文件已经满足当前 Rust validation contract 时不重复转换。"
    static let categorizeOutput = "按拍摄模式分类输出"
    static let categorizeOutputHelp = "根据源照片的 OPPO UserComment，将转换结果写入普通拍照、大师模式、专业模式、人像等子目录；无法可靠识别的文件保留在输出根目录。"
    static let concurrentJobs = "并发任务"
    static let outputFileSuffix = "输出文件后缀"
    static let outputFileSuffixHelp = "未设置输出目录时，在原目录用这个后缀生成新文件。"
    static let outputDirectory = "输出目录"
    static let done = "完成"
    static let useOriginalDirectory = "使用原目录"
    static let chooseDirectory = "选择目录"
    static let clear = "清除"

}
