#!/usr/bin/env python3
"""Prepare and train the shared Apple ReverseKey1Net."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from xdremux_py.apple_reverse_key1_training import (
    PreparationConfig,
    TrainingConfig,
    prepare_dataset,
    storage_summary,
    train,
    verify_training_run,
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    prepare = subparsers.add_parser("prepare", help="build a resumable native cache")
    prepare.add_argument("--corpus", required=True, type=Path)
    prepare.add_argument("--output", required=True, type=Path)
    prepare.add_argument("--helper", required=True, type=Path)
    prepare.add_argument("--exiftool", default="exiftool")
    prepare.add_argument("--workers", type=int, default=4)
    prepare.add_argument("--max-cache-gib", type=float, default=4.0)

    training = subparsers.add_parser("train", help="train ReverseKey1Net")
    training.add_argument("--manifest", required=True, type=Path)
    training.add_argument("--output", required=True, type=Path)
    training.add_argument("--epochs", type=int, default=60)
    training.add_argument("--batch-size", type=int, default=8)
    training.add_argument("--learning-rate", type=float, default=2e-4)
    training.add_argument("--seed", type=int, default=260819)
    training.add_argument("--device", choices=("auto", "mps", "cpu"), default="auto")
    training.add_argument("--num-workers", type=int, default=0)
    training.add_argument(
        "--profile-conditioning",
        choices=("none", "target_device_model"),
        default="none",
    )
    training.add_argument("--balance-profiles", action="store_true")
    training.add_argument("--initialize-from", type=Path)
    training.add_argument("--base-learning-rate-scale", type=float, default=0.1)
    training.add_argument(
        "--architecture",
        choices=("small", "multiscale_large"),
        default="small",
    )
    training.add_argument("--horizontal-flip-probability", type=float, default=0.0)
    training.add_argument("--checkpoint-interval", type=int, default=1)
    training.add_argument(
        "--single-image-self-pair",
        action="store_true",
        help="explicitly duplicate styled primary as the paired input",
    )

    storage = subparsers.add_parser("storage", help="report exact generated bytes")
    storage.add_argument("paths", nargs="+", type=Path)

    verify = subparsers.add_parser("verify", help="verify a completed offline run")
    verify.add_argument("--manifest", required=True, type=Path)
    verify.add_argument("--run", required=True, type=Path)

    args = parser.parse_args()
    if args.command == "prepare":
        result = prepare_dataset(
            PreparationConfig(
                corpus=args.corpus,
                output=args.output,
                helper=args.helper,
                exiftool=args.exiftool,
                workers=args.workers,
                maximum_output_bytes=int(args.max_cache_gib * 1024**3),
            )
        )
    elif args.command == "train":
        result = train(
            TrainingConfig(
                manifest=args.manifest,
                output=args.output,
                epochs=args.epochs,
                batch_size=args.batch_size,
                learning_rate=args.learning_rate,
                seed=args.seed,
                device=args.device,
                num_workers=args.num_workers,
                profile_conditioning=args.profile_conditioning,
                balance_profiles=args.balance_profiles,
                initialize_from=args.initialize_from,
                base_learning_rate_scale=args.base_learning_rate_scale,
                architecture=args.architecture,
                horizontal_flip_probability=args.horizontal_flip_probability,
                checkpoint_interval=args.checkpoint_interval,
                single_image_self_pair=args.single_image_self_pair,
            )
        )
    elif args.command == "storage":
        result = storage_summary(args.paths)
    else:
        result = verify_training_run(args.manifest, args.run)
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
