#import <Foundation/Foundation.h>
#import <ImageIO/ImageIO.h>
#import <CoreGraphics/CoreGraphics.h>
#import <objc/message.h>
#import <objc/runtime.h>
#import <dlfcn.h>

static void ReleaseProviderData(void *info, const void *data, size_t size) { (void)info; (void)size; free((void *)data); }

static id SafeObject(id obj) {
    if (!obj) return [NSNull null];
    if ([obj isKindOfClass:[NSString class]] || [obj isKindOfClass:[NSNumber class]] || [obj isKindOfClass:[NSNull class]]) return obj;
    if ([obj isKindOfClass:[NSData class]]) return @{ @"class":NSStringFromClass([obj class]), @"bytes":@([(NSData *)obj length]) };
    if ([obj isKindOfClass:[NSArray class]]) { NSMutableArray *a=[NSMutableArray array]; for(id v in (NSArray *)obj)[a addObject:SafeObject(v)]; return a; }
    if ([obj isKindOfClass:[NSDictionary class]]) { NSMutableDictionary *d=[NSMutableDictionary dictionary]; for(id k in (NSDictionary *)obj)d[[k description]]=SafeObject([(NSDictionary *)obj objectForKey:k]); return d; }
    NSMutableDictionary *d=[@{ @"class":NSStringFromClass([obj class])?:@"<unknown>", @"description":[obj description]?:@"<nil>" } mutableCopy];
    for(NSString *k in @[ @"preset",@"intensity",@"grain",@"version",@"captureMode",@"captureType",@"hardwareModel",@"portType",@"filmGrainSeed",@"numberOfPersons" ]) @try { id v=[obj valueForKey:k]; if(v)d[k]=SafeObject(v); } @catch(__unused NSException *e){}
    return d;
}

static void *LookupSymbol(NSString *name) {
    void *p=dlsym(RTLD_DEFAULT,name.UTF8String); if(p)return p;
    if([name hasPrefix:@"_"]&&name.length>1){ p=dlsym(RTLD_DEFAULT,[[name substringFromIndex:1] UTF8String]); if(p)return p; }
    else { NSString *u=[@"_" stringByAppendingString:name]; p=dlsym(RTLD_DEFAULT,u.UTF8String); if(p)return p; }
    return NULL;
}
static id ObjectSymbol(NSString *name) {
    void *p=LookupSymbol(name); if(!p)return nil;
    @try { __unsafe_unretained id v=*(__unsafe_unretained id *)p; return v?:[NSNull null]; }
    @catch(NSException *e){ return @{ @"address":[NSString stringWithFormat:@"%p",p], @"exception":e.reason?:e.name }; }
}
static id CallClass0(NSString *cn,NSString *sn){ Class c=NSClassFromString(cn); SEL s=NSSelectorFromString(sn); if(!c||![c respondsToSelector:s])return nil; @try{return((id(*)(id,SEL))objc_msgSend)(c,s);}@catch(NSException*e){return@{@"exception":e.reason?:e.name};}}
static id CallClass1(NSString *cn,NSString *sn,id a){ Class c=NSClassFromString(cn); SEL s=NSSelectorFromString(sn); if(!c||![c respondsToSelector:s])return nil; @try{return((id(*)(id,SEL,id))objc_msgSend)(c,s,a);}@catch(NSException*e){return@{@"exception":e.reason?:e.name};}}
static id CallInstance0(NSString *cn,NSString *sn){ Class c=NSClassFromString(cn); if(!c)return nil; id o=nil; @try{o=[[c alloc]init];}@catch(__unused NSException*e){return nil;} SEL s=NSSelectorFromString(sn); if(!o||![o respondsToSelector:s])return nil; @try{return((id(*)(id,SEL))objc_msgSend)(o,s);}@catch(NSException*e){return@{@"exception":e.reason?:e.name};}}

static NSDictionary *ClassSurface(NSString *name){ Class c=NSClassFromString(name); if(!c)return@{@"available":@NO}; NSMutableArray *cm=[NSMutableArray array],*im=[NSMutableArray array]; unsigned int n=0; Method *m=class_copyMethodList(object_getClass(c),&n); for(unsigned int i=0;i<n;i++) [cm addObject:NSStringFromSelector(method_getName(m[i]))]; free(m); n=0;m=class_copyMethodList(c,&n);for(unsigned int i=0;i<n;i++)[im addObject:NSStringFromSelector(method_getName(m[i]))];free(m);[cm sortUsingSelector:@selector(compare:)];[im sortUsingSelector:@selector(compare:)];return@{@"available":@YES,@"classMethods":cm,@"instanceMethods":im};}

static NSDictionary *TextureTrial(NSDictionary *image,NSDictionary *aux){ Class c=NSClassFromString(@"_NUTextureStyleProperties");SEL s=NSSelectorFromString(@"textureStylePropertiesFromImageMetadata:auxImageMetadata:error:");if(!c||![c respondsToSelector:s])return@{@"available":@NO};NSError *err=nil;id r=nil;@try{r=((id(*)(id,SEL,id,id,NSError**))objc_msgSend)(c,s,image,aux,&err);}@catch(NSException*e){return@{@"available":@YES,@"exception":e.reason?:e.name};}NSMutableDictionary*d=[NSMutableDictionary dictionaryWithObject:@YES forKey:@"available"];d[@"result"]=SafeObject(r);if(err){d[@"errorDomain"]=err.domain?:@"";d[@"errorCode"]=@(err.code);d[@"errorDescription"]=err.localizedDescription?:err.description;d[@"errorUserInfo"]=SafeObject(err.userInfo);}return d;}

static CGImageRef TinyImage(void){size_t w=8,h=8,bpr=w*4;uint8_t*b=calloc(h,bpr);for(size_t y=0;y<h;y++)for(size_t x=0;x<w;x++){size_t i=y*bpr+x*4;b[i]=(uint8_t)(x*32);b[i+1]=(uint8_t)(y*32);b[i+2]=128;b[i+3]=255;}CGDataProviderRef p=CGDataProviderCreateWithData(NULL,b,h*bpr,ReleaseProviderData);CGColorSpaceRef cs=CGColorSpaceCreateDeviceRGB();CGImageRef im=CGImageCreate(w,h,8,32,bpr,cs,kCGBitmapByteOrderDefault|kCGImageAlphaLast,p,NULL,false,kCGRenderingIntentDefault);CGColorSpaceRelease(cs);CGDataProviderRelease(p);return im;}
static NSDictionary *WriteReadJPEG(NSURL *url,NSDictionary *maker){CGImageRef im=TinyImage();CGImageDestinationRef d=CGImageDestinationCreateWithURL((__bridge CFURLRef)url,CFSTR("public.jpeg"),1,NULL);NSDictionary*p=@{(__bridge NSString*)kCGImagePropertyMakerAppleDictionary:maker,(__bridge NSString*)kCGImagePropertyTIFFDictionary:@{(__bridge NSString*)kCGImagePropertyTIFFMake:@"Apple",(__bridge NSString*)kCGImagePropertyTIFFModel:@"iPhone17,1"}};BOOL ok=NO;if(d){CGImageDestinationAddImage(d,im,(__bridge CFDictionaryRef)p);ok=CGImageDestinationFinalize(d);CFRelease(d);}CGImageRelease(im);NSMutableDictionary*out=[NSMutableDictionary dictionaryWithObject:@(ok) forKey:@"finalized"];if(ok){CGImageSourceRef s=CGImageSourceCreateWithURL((__bridge CFURLRef)url,NULL);if(s){CFDictionaryRef r=CGImageSourceCopyPropertiesAtIndex(s,0,NULL);if(r){out[@"readback"]=SafeObject((__bridge NSDictionary*)r);CFRelease(r);}CFRelease(s);}NSDictionary*a=[[NSFileManager defaultManager]attributesOfItemAtPath:url.path error:nil];out[@"bytes"]=a[NSFileSize]?:@0;}return out;}

static NSDictionary *BuildProbe(NSURL *outputDir){
    NSArray *frameworks=@[@"/System/Library/PrivateFrameworks/CMImaging.framework/CMImaging",@"/System/Library/PrivateFrameworks/CMCaptureCore.framework/CMCaptureCore",@"/System/Library/PrivateFrameworks/AVFCapture.framework/AVFCapture",@"/System/Library/PrivateFrameworks/NeutrinoCore.framework/NeutrinoCore",@"/System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging",@"/System/Library/PrivateFrameworks/PhotosFormats.framework/PhotosFormats",@"/System/Library/PrivateFrameworks/CameraEditKit.framework/CameraEditKit"];
    NSMutableDictionary*loaded=[NSMutableDictionary dictionary];for(NSString*p in frameworks)loaded[p]=@(dlopen(p.UTF8String,RTLD_NOW|RTLD_GLOBAL)!=NULL);
    NSArray *sn=@[@"AVAppleMakerNote_TextureStyleKey_Preset",@"AVAppleMakerNote_TextureStyleKey_Intensity",@"AVAppleMakerNote_TextureStyleKey_Grain",@"AVAppleMakerNote_TextureStyleKey_RenderingVersion",@"AVAppleMakerNote_TextureStyleKey_OriginalInsteadOfReversibility",@"kFigAppleMakerNote_TextureStyleKey_Preset",@"kFigAppleMakerNote_TextureStyleKey_Intensity",@"kFigAppleMakerNote_TextureStyleKey_Grain",@"kFigAppleMakerNote_TextureStyleKey_RenderingVersion",@"kFigAppleMakerNote_TextureStyleKey_OriginalInsteadOfReversibility",@"PITextureStyleAdjustmentKey",@"AVCaptureTextureStylePresetStandard",@"AVCaptureTextureStylePresetStudio",@"AVCaptureTextureStylePresetSoft",@"AVCaptureTextureStylePresetFilmic",@"AVCaptureTextureStylePresetGlowy",@"AVCaptureTextureStylePresetPreview",@"kFigCaptureSampleBufferMetadata_TextureStylePreset",@"kFigCaptureSampleBufferMetadata_TextureStylePresetTunings",@"kFigCaptureSampleBufferMetadata_TextureStylePeopleDataVersion",@"kFigCaptureSampleBufferMetadata_TextureStylePostProcessedPeopleData",@"kFigCaptureSampleBufferAttachedMediaKey_TextureStyleFaceAttitudeMetadata"];
    NSMutableDictionary*symbols=[NSMutableDictionary dictionary];for(NSString*n in sn){id v=ObjectSymbol(n);symbols[n]=v?SafeObject(v):[NSNull null];}
    NSArray *classes=@[@"AVCaptureTextureStyle",@"CMITextureStyle",@"CMITextureStyleTuningLookup",@"_NUTextureStyleProperties",@"_NUTextureStylePersonInstanceProperties",@"PIAdjustmentConstants",@"PISchema",@"PITextureStyle",@"PITextureStyleAdjustmentController",@"PITextureStyleAutoCalculator",@"PITextureStylePipelineProcessor",@"PFMetadata",@"PFMetadataImage"];
    NSMutableDictionary*surfaces=[NSMutableDictionary dictionary];for(NSString*n in classes)surfaces[n]=ClassSurface(n);
    NSMutableDictionary*api=[NSMutableDictionary dictionary];NSArray*calls=@[@[@"PISchema",@"textureStyleSchema"],@[@"PITextureStyle",@"identifier"],@[@"PITextureStyle",@"adjustmentFormat"],@[@"PITextureStyle",@"adjustmentDescriptor"],@[@"PITextureStyle",@"availableOptions"],@[@"PITextureStyleAdjustmentController",@"allPresets"],@[@"PITextureStyleAdjustmentController",@"presetKey"],@[@"PITextureStyleAdjustmentController",@"intensityKey"],@[@"PITextureStyleAdjustmentController",@"grainIntensityKey"],@[@"AVCaptureTextureStyle",@"identityStyle"],@[@"CMITextureStyle",@"initStandardTextureStyle"]];for(NSArray*c in calls){id v=CallClass0(c[0],c[1]);api[[NSString stringWithFormat:@"%@.%@",c[0],c[1]]]=v?SafeObject(v):[NSNull null];}id av=CallInstance0(@"PIAdjustmentConstants",@"PITextureStyleAdjustmentKey");api[@"PIAdjustmentConstants(instance).PITextureStyleAdjustmentKey"]=av?SafeObject(av):[NSNull null];
    for(NSString*p in @[@"Standard",@"Studio",@"Soft",@"Filmic",@"Glowy",@"Preview"]){id v=CallClass1(@"CMITextureStyleTuningLookup",@"defaultTextureStyleForPresetName:",p);api[[NSString stringWithFormat:@"CMITextureStyleTuningLookup.default.%@",p]]=v?SafeObject(v):[NSNull null];}
    NSDictionary*fallback=@{@"Preset":@"Standard",@"Intensity":@1.0,@"Grain":@0.0,@"RenderingVersion":@1,@"OriginalInsteadOfReversibility":@NO};NSDictionary*map=@{@"Preset":@"AVAppleMakerNote_TextureStyleKey_Preset",@"Intensity":@"AVAppleMakerNote_TextureStyleKey_Intensity",@"Grain":@"AVAppleMakerNote_TextureStyleKey_Grain",@"RenderingVersion":@"AVAppleMakerNote_TextureStyleKey_RenderingVersion",@"OriginalInsteadOfReversibility":@"AVAppleMakerNote_TextureStyleKey_OriginalInsteadOfReversibility"};NSMutableDictionary*maker=[NSMutableDictionary dictionary];for(NSString*l in fallback){id k=ObjectSymbol(map[l]);if(!k||k==[NSNull null])k=l;maker[k]=fallback[l];}
    NSDictionary*full=@{@"TextureStyleVersion":@1,@"Version":@1,@"CaptureMode":@"Photo",@"CaptureType":@"Photo",@"HardwareModel":@"iPhone17,1",@"PortType":@"BackWide",@"FilmGrainSeed":@1,@"Preset":@"Standard",@"Intensity":@1.0,@"Grain":@0.0,@"RenderingVersion":@1,@"OriginalInsteadOfReversibility":@NO};NSDictionary*mc=@{(__bridge NSString*)kCGImagePropertyMakerAppleDictionary:maker};NSDictionary*fc=@{(__bridge NSString*)kCGImagePropertyMakerAppleDictionary:full};NSDictionary*imageIO=WriteReadJPEG([outputDir URLByAppendingPathComponent:@"texture-style-imageio-probe.jpg"],maker);NSDictionary*readback=[imageIO[@"readback"]isKindOfClass:[NSDictionary class]]?imageIO[@"readback"]:@{};
    NSDictionary*trials=@{@"empty":TextureTrial(@{},@{}),@"makerStyleOnly":TextureTrial(mc,@{}),@"directStyleOnly":TextureTrial(maker,@{}),@"makerFullGuessed":TextureTrial(fc,@{}),@"directFullGuessed":TextureTrial(full,@{}),@"auxFullGuessed":TextureTrial(@{},full),@"makerStyleAuxFull":TextureTrial(mc,full),@"imageIOReadback":TextureTrial(readback,@{})};id tm=CallClass1(@"CMITextureStyleTuningLookup",@"tuningDictionaryForMetadata:",maker);id tf=CallClass1(@"CMITextureStyleTuningLookup",@"tuningDictionaryForMetadata:",full);
    return@{@"os":NSProcessInfo.processInfo.operatingSystemVersionString,@"frameworks":loaded,@"symbols":symbols,@"classes":surfaces,@"api":api,@"makerDictionary":SafeObject(maker),@"imageIOProbe":imageIO,@"texturePropertiesTrials":trials,@"tuningFromMaker":tm?SafeObject(tm):[NSNull null],@"tuningFromFullGuessed":tf?SafeObject(tf):[NSNull null]};
}

int main(int argc,const char *argv[]){@autoreleasepool{NSString*dir=(argc>1)?[NSString stringWithUTF8String:argv[1]]:@".";NSURL*out=[NSURL fileURLWithPath:dir isDirectory:YES];[[NSFileManager defaultManager]createDirectoryAtURL:out withIntermediateDirectories:YES attributes:nil error:nil];NSDictionary*p=BuildProbe(out);NSData*j=[NSJSONSerialization dataWithJSONObject:p options:NSJSONWritingPrettyPrinted|NSJSONWritingSortedKeys error:nil];[j writeToURL:[out URLByAppendingPathComponent:@"texture-style-macos27-probe-v2.json"] atomically:YES];fwrite(j.bytes,1,j.length,stdout);fputc('\n',stdout);return 0;}}
